### PR TITLE
Add Report for SoupX

### PR DESCRIPTION
**Pull request by mvfki**
Josh, maybe we can merge it a bit later because I want to also work on fixing GitHub Action stuff.

### CODE REVIEW

**Comment by mvfki** [comment]
@joshua-d-campbell , I think it's ok to merge it this time if we pass the Checks.


@rz2333 @ykoga07 , When I worked on `cnsl_cellqc.Rmd`, I found there were some issues with Scrublet. In older version of the doc, we had a filter on `scrublet_call`, which was a logical vector (i.e. `TRUE`/`FALSE`). This time when I reran the `pkgdown::build_article` command, the `scrublet_call` vector became character and has values of `"Singlet"`/`"Doublet"`. I have changed the filtering arguments to `colData = 'scrublet_call == "Singlet"'`. I'm wondering if this is due to an update from scrublet.


@joshua-d-campbell , @irzamsarfraz , @rz2333 , @ykoga07 , 
Besides, the behavior of pkgdown seems also has changed. Previously when we have an RMD file at `vignettes/articles/doc.Rmd`, the output HTML file will be at `docs/articles/articles/doc.html`, but now the output goes to `docs/articles/doc.html`, at least on my local machine (probably because I accidentally updated pkgdown). And it seems RMD at `vignettes/doc.Rmd` also goes to the same destination. So maybe we would have to decide whether to keep the older structure and ask somebody who has the older version of pkgdown to render it, or Otherwise, we will need to take care of some in-site links and then rebuilt the whole site. Personally, I would say the new version looks better because the URL can finally be clean. And if we decide to rebuild the site with the new version, I can quickly go through all the links to check if there's anything broken.

**Comment by rz2333** [comment]
@mvfki Thanks for pointing out the second point. Yes, we have updated the output of scrublet call but didn't update that in the doc. For the pkgdown, could you list the package version?

**Comment by mvfki** [comment]
> @mvfki Thanks for pointing out the second point. Yes, we have updated the output of scrublet call but didn't update that in the doc. For the pkgdown, could you list the package version?

```
> package.version("pkgdown")
[1] "2.0.1"
```

**Comment by irzamsarfraz** [comment]
@mvfki Yichen, are all the examples added? I saw that BiocCheck was passing and also noticed that you added some examples for exp functions. Let me know seurat ones are required. Sorry, I got a little late.

**Comment by mvfki** [comment]
@irzamsarfraz I just added examples for exp functions. Since the BioC checks are already passing, I don't think we need to prioritize this for now.

**Comment by irzamsarfraz** [comment]
Okay, sounds good. Thanks!

**Pull request merged**
