### PR TITLE
scanpyNormalizeData function

### PR DESCRIPTION
**Pull request by npervaiz**

### CODE REVIEW

**Comment by irzamsarfraz** [comment]
@joshua-d-campbell Could you merge this please? It has errors but I believe Nida is fixing one of them and I'll work on the others.

**Comment by mvfki** [comment]
@irzamsarfraz @npervaiz Just make sure to revisit this file later after you guys fixed the issues. There are some conventions that should have been followed.

**Comment by irzamsarfraz** [comment]
> @irzamsarfraz @npervaiz Just make sure to revisit this file later after you guys fixed the issues. There are some conventions that should have been followed.

I'll be following the conventions used with the scrublet function to edit this and any new functions we make. The scrublet function is updated, right?

**Comment by joshua-d-campbell** [comment]
@irzamsarfraz Can you just checkout this PR locally for now and then we can merge latter when the errors are fixed and the function is clean? Here is info:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by irzamsarfraz** [comment]
Hey Josh, latest version of TSCAN package was pushed to BioC and these checks have passed. Could you merge it?

@joshua-d-campbell @npervaiz

**Pull request closed without merging**
